# action.yml
name: 'Wiki Update Tracker'
description: 'Track translation files diff from original files in a git repo, generate files and instruct translators'
inputs:
  log-level:
    description: 'The python script log level, either CRITICAL, ERROR, WARNING, INFO, DEBUG or NOTSET'
    required: false
    default: "INFO"
  # 1) Backtracking
  repo-path:
    description: 'The local path of the checked-out git repository, make sure you checkout on the desired branch'
    required: true
  original:
    description: 'Path to the directory containing original files, relative to repo-path'
    required: true
  filters:
    description: 'Glob patterns matching files to track within original path and translation paths'
    required: false
    default: |
      **/*
  ignores:
    description: 'Glob patterns matching files to ignore when parsing original files, relative to repo-path'
    required: false
    default: ''
  translations:
    description: 'Paths to the directories containing translation files, relative to repo-path, along with their associated language tag'
    required: true
  # 2) Auto generation
  gen-stubs:
    description: 'Automatically create stubs for To Create translation files matching one of the given fnmatch patterns, with content defined by stub-template - checked-out repository must have be able to push to destination branch (gen-branch)'
    required: false
    default: ''
  stub-commit:
    description: 'The commit message when generating stub files'
    required: false
    default: ':tada: Created stub translation files'
  stub-template:
    description: 'Template file defining the content of generated stub files - more info about templates here: https://github.com/Awagi/wiki-update-tracker#about-templates'
    required: false
    default: ''
  gen-copy:
    description: 'Automatically copy original files to To Create translation files matching one of the given fnmatch patterns - checked-out repository must have be able to push to destination branch (gen-branch)'
    required: false
    default: ''
  copy-commit:
    description: 'The commit message when generating file copies'
    required: false
    default: ':tada: Copied original to translation files'
  gen-branch:
    description: 'The branch where files will be pushed when auto generating changes - empty name means files will be committed to the checked-out repository active branch - the branch must exist and be not protected'
    required: false
    default: ''
  # 3) Instructing
  repository:
    description: 'The GitHub repository, in the form "Author/repo"'
    required: false
    default: "${{ github.repository }}"
  token:
    description: 'The authorization token to update issues, projects and pull requests - make sure the GitHub App has enough permissions to update these (and no more)'
    required: false
    default: "${{ github.token }}"
  request-merge:
    description: 'Request merging gen-branch (if set and if changes were applied) to checked-out repository active branch through a Pull Request - GitHub App token requires read/write access to Pull Requests'
    required: false
    default: 'false'
  instruct-issues:
    description: 'Instruct translators on translation files matching one of the given fnmatch patterns through GitHub Issues - GitHub App token requires read/write access to Issues in repository'
    required: false
    default: ''
  issue-label:
    description: "The label name used by the Update Tracker to manage issues, other issues won't be seen"
    required: false
    default: 'translation-tracker'
  issue-title-template:
    description: 'The issue title template - the resulting issue title must be unique, keep {t.translation.path} in the template'
    required: false
    default: 'Translation file: {t.translation.path}'
  issue-create-template:
    description: 'The issue body template file for To Create translation files - more info about templates here: https://github.com/Awagi/wiki-update-tracker#about-templates'
    required: false
    default: ''
  issue-initialize-template:
    description: 'The issue body template file for To Initialize translation files - more info about templates here: https://github.com/Awagi/wiki-update-tracker#about-templates'
    required: false
    default: ''
  issue-update-template:
    description: 'The issue body template file for To Update translation files - more info about templates here: https://github.com/Awagi/wiki-update-tracker#about-templates'
    required: false
    default: ''
  issue-uptodate-template:
    description: 'The issue body template file for Up-To-Date translation files - more info about templates here: https://github.com/Awagi/wiki-update-tracker#about-templates'
    required: false
    default: ''
  issue-orphan-template:
    description: 'The issue body template file for Orphan translation files - more info about templates here: https://github.com/Awagi/wiki-update-tracker#about-templates'
    required: false
    default: ''
  instruct-projects:
    description: 'Instruct translators on translation files matching one of the given fnmatch patterns through GitHub Projects - Github App token requires read/write access to Projects in repository'
    required: false
    default: ''
  project-title-template:
    description: 'The project name template - more info about templates here: https://github.com/Awagi/wiki-update-tracker#about-templates'
    required: false
    default: '{t.translation.language} Update Tracker'
  project-description-template:
    description: 'The project description template when it is created - more info about templates here: https://github.com/Awagi/wiki-update-tracker#about-templates'
    required: false
    default: '{t.translation.language} translation effort.'
  project-column-create-template:
    description: 'The column template in project to include To Create translation file cards - more info about templates here: https://github.com/Awagi/wiki-update-tracker#about-templates'
    required: false
    default: 'To Initialize'
  project-column-initialize-template:
    description: 'The column template in project to include To Initialize translation file cards - more info about templates here: https://github.com/Awagi/wiki-update-tracker#about-templates'
    required: false
    default: 'To Initialize'
  project-column-update-template:
    description: 'The column template in project to include To Update translation file cards - more info about templates here: https://github.com/Awagi/wiki-update-tracker#about-templates'
    required: false
    default: 'To Update'
  project-column-uptodate-template:
    description: 'The column template in project to include Up-To-Date translation file cards - more info about templates here: https://github.com/Awagi/wiki-update-tracker#about-templates'
    required: false
    default: 'Up-To-Date'
  project-column-orphan-template:
    description: 'The column template in project to include Orphan translation file cards - more info about templates here: https://github.com/Awagi/wiki-update-tracker#about-templates'
    required: false
    default: 'Orphans'
  project-card-create-template:
    description: 'The card template file in project column for To Create translation files - more info about templates here: https://github.com/Awagi/wiki-update-tracker#about-templates'
    required: false
    default: ''
  project-card-initialize-template:
    description: 'The card template file in project column for To Initialize translation files - more info about templates here: https://github.com/Awagi/wiki-update-tracker#about-templates'
    required: false
    default: ''
  project-card-update-template:
    description: 'The card template file in project column for To Update translation files - more info about templates here: https://github.com/Awagi/wiki-update-tracker#about-templates'
    required: false
    default: ''
  project-card-uptodate-template:
    description: 'The card template file in project column for Up-To-Date translation files - more info about templates here: https://github.com/Awagi/wiki-update-tracker#about-templates'
    required: false
    default: ''
  project-card-orphan-template:
    description: 'The card template file in project column for Orphan translation files - more info about templates here: https://github.com/Awagi/wiki-update-tracker#about-templates'
    required: false
    default: ''

outputs:
  translation-tracks: 
    description: 'Tracked info for every translation files as a application/json format'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    # order from entrypoint.sh
    - ${{ inputs.log-level }} # 1
    - ${{ inputs.repo-path }} # 2
    - ${{ inputs.original }} # 3
    - ${{ inputs.translations }} # 4
    - ${{ inputs.filters }} # 5
    - ${{ inputs.ignores }} # 6
    - ${{ inputs.gen-stubs }} # 7
    - ${{ inputs.stub-commit }} # 8
    - ${{ inputs.stub-template }} # 9
    - ${{ inputs.gen-copy }} # 10
    - ${{ inputs.copy-commit }} # 11
    - ${{ inputs.gen-branch }} # 12
    - ${{ inputs.repository }} # 13
    - ${{ inputs.token }} # 14
    - ${{ inputs.request-merge }} # 15
    - ${{ inputs.instruct-issues }} # 16
    - ${{ inputs.issue-label }} # 17
    - ${{ inputs.issue-title-template }} # 18
    - ${{ inputs.issue-create-template }} # 19
    - ${{ inputs.issue-initialize-template }} # 20
    - ${{ inputs.issue-update-template }} # 21
    - ${{ inputs.issue-uptodate-template }} # 22
    - ${{ inputs.issue-orphan-template }} # 23
    - ${{ inputs.instruct-projects }} # 24
    - ${{ inputs.project-title-template }} # 25
    - ${{ inputs.project-description-template }} # 26
    - ${{ inputs.project-column-create-template }} # 27
    - ${{ inputs.project-column-initialize-template }} # 28
    - ${{ inputs.project-column-update-template }} # 29
    - ${{ inputs.project-column-uptodate-template }} # 30
    - ${{ inputs.project-column-orphan-template }} # 31
    - ${{ inputs.project-card-create-template }} # 32
    - ${{ inputs.project-card-initialize-template }} # 33
    - ${{ inputs.project-card-update-template }} # 34
    - ${{ inputs.project-card-uptodate-template }} # 35
    - ${{ inputs.project-card-orphan-template }} # 36
