name: BSMG Wiki Translation Update Tracker

on:
  push:
    branches: [master]

jobs:
  track:
    runs-on: ubuntu-latest

    steps:
      - name: Get custom App JWT
        id: get_token
        uses: machine-learning-apps/actions-app-token@0.21
        with:
          APP_PEM: ${{ secrets.APP_PEM }}
          APP_ID: ${{ secrets.APP_ID }}

      # Checkout is necessary to create the git repository
      - name: Checkout git repository
        uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: 0
          token: ${{ steps.get_token.outputs.app_token }}

      - name: Check original pages status and update translation Projects
        uses: Awagi/wiki-update-tracker@v1.8
        with:
          # Checked-out repo path
          repo-path: $GITHUB_WORKSPACE
          # BACKTRACKING
          original-path: "wiki"
          translations: |
            fr:wiki/fr
          filter: |
            **/*
          exclude: |
            docs/.vuepress/**
          # AUTO GENERATION
          branch-gen: "wut-auto"
          request-merge: "true"
          gen-stubs: |
            *.md
          stub-commit-msg: ":tada: Creating stub translation pages"
          stub-template: "bsmg-wiki-update-tracker/gen-stub-template.md"
          gen-copy: |
            *.png
          # INSTRUCTING
          token: ${{ steps.get_token.outputs.app_token }}
          instruct-projects: |
            *.md
          project-title-template: "Wiki {t.translation.language} Update Tracker"
          project-description-template: "{t.translation.language} translation effort."
          project-column-create-template: "To Initialize"
          project-column-initialize-template: "To Initialize"
          project-column-update-template: "To Update"
          project-column-uptodate-template: "Up-To-Date"
          project-column-orphan-template: "Orphans"
          project-card-create-template: "bsmg-wiki-update-tracker/project-create-template.md"
          project-card-initialize-template: "bsmg-wiki-update-tracker/project-initialize-template.md"
          project-card-update-template: "bsmg-wiki-update-tracker/project-update-template.md"
          project-card-uptodate-template: "bsmg-wiki-update-tracker/project-uptodate-template.md"
          project-card-orphan-template: "bsmg-wiki-update-tracker/project-orphan-template.md"

